# backend/dev_tools/mock_groq_server.py
"""
DEV-ONLY TOOL — not part of the production deliverable.

A minimal FastAPI app that mimics Groq's OpenAI-compatible chat completions
endpoint shape, used only to prove the full VERA pipeline works end-to-end
over real HTTP in network-restricted environments (e.g. a sandbox where
api.groq.com is blocked by an egress allowlist). It returns a deterministic,
content-aware "composition" so generated output can be inspected for
correctness (uses real trigger/merchant context fields embedded in the
prompt to build a plausible body, rather than a static placeholder).

Run (from backend/ directory):
    uvicorn dev_tools.mock_groq_server:app --host 0.0.0.0 --port 9001
Then point the real bot at it:
    GROQ_BASE_URL=http://localhost:9001/openai/v1
"""
import json
import re
import time

from fastapi import FastAPI, Request

app = FastAPI()


def _extract(pattern: str, text: str, default: str = "") -> str:
    m = re.search(pattern, text)
    return m.group(1).strip() if m else default


@app.post("/openai/v1/chat/completions")
async def chat_completions(request: Request):
    body = await request.json()
    messages = body.get("messages", [])
    user_msg = next((m["content"] for m in messages if m["role"] == "user"), "")
    system_msg = next((m["content"] for m in messages if m["role"] == "system"), "")

    owner = _extract(r"owner_first_name:\s*(\S+)", user_msg, "there")
    trigger_kind = _extract(r"kind:\s*(\S+)", user_msg, "update")
    merchant_name = _extract(r"name:\s*([^\n]+)", user_msg, "your business")

    is_customer_scoped = "CUSTOMER CONTEXT" in user_msg
    send_as = "merchant_on_behalf" if is_customer_scoped else "vera"

    composed = {
        "body": (
            f"Hi {owner}, quick note on your {trigger_kind.replace('_', ' ')} — "
            f"this is a mock composition for {merchant_name.strip()} generated by the "
            f"sandbox test double, anchored on the real trigger/merchant context fields above."
        ),
        "cta": "open_ended",
        "send_as": send_as,
        "template_params": [owner, trigger_kind, "open_ended"],
        "rationale": f"Mock composition anchored on the {trigger_kind} trigger signal for testing purposes.",
    }

    return {
        "id": "mock-completion",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": body.get("model", "mock-model"),
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": json.dumps(composed)},
                "finish_reason": "stop",
            }
        ],
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }
