#!/usr/bin/env python3
"""
generate_submission.py — produces submission.jsonl (30 lines, one per
canonical test pair) per challenge-brief.md §7.2, by driving the ACTUAL
deployed/running bot through its real HTTP API (/v1/context, /v1/tick) —
not by re-implementing composition logic separately. This guarantees the
submission file reflects exactly what the live bot would say, since it's
generated by exercising the exact same code path the judge harness uses.

Usage:
    # 1. Start the bot (with a real GROQ_API_KEY configured):
    uvicorn main:app --host 0.0.0.0 --port 8080

    # 2. In another terminal, point this script at it and run:
    export BOT_URL=http://localhost:8080
    python3 generate_submission.py --expanded-dir ../expanded --out ../submission.jsonl

Each output line has exactly the fields challenge-brief.md §7.2 expects:
    {"test_id": "...", "body": "...", "cta": "...", "send_as": "...",
     "suppression_key": "...", "rationale": "..."}
"""
import argparse
import json
import os
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

import httpx

DEFAULT_BOT_URL = os.getenv("BOT_URL", "http://localhost:8080")


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def push_context(client: httpx.Client, scope: str, context_id: str, payload: dict, version: int = 1) -> None:
    resp = client.post("/v1/context", json={
        "scope": scope,
        "context_id": context_id,
        "version": version,
        "payload": payload,
        "delivered_at": datetime.utcnow().isoformat() + "Z",
    })
    resp.raise_for_status()


def safe_now_before_expiry(trigger_payload: dict, fallback: str = "2026-04-26T10:35:00Z") -> str:
    expires = trigger_payload.get("expires_at")
    if not expires:
        return fallback
    try:
        expires_dt = datetime.fromisoformat(expires.replace("Z", "+00:00"))
        return (expires_dt - timedelta(hours=1)).isoformat().replace("+00:00", "Z")
    except ValueError:
        return fallback


def main():
    parser = argparse.ArgumentParser(description="Generate submission.jsonl by driving the live bot.")
    parser.add_argument("--bot-url", default=DEFAULT_BOT_URL, help="Base URL of the running bot")
    parser.add_argument("--expanded-dir", default="../expanded", help="Path to expanded dataset dir")
    parser.add_argument("--out", default="../submission.jsonl", help="Output path for submission.jsonl")
    parser.add_argument("--timeout", type=float, default=35.0, help="Per-request HTTP timeout (s)")
    args = parser.parse_args()

    expanded_dir = Path(args.expanded_dir)
    test_pairs_path = expanded_dir / "test_pairs.json"
    if not test_pairs_path.exists():
        print(f"ERROR: {test_pairs_path} not found. Run dataset/generate_dataset.py first.", file=sys.stderr)
        sys.exit(1)

    pairs = load_json(test_pairs_path)["pairs"]
    print(f"Loaded {len(pairs)} canonical test pairs.")

    client = httpx.Client(base_url=args.bot_url, timeout=args.timeout)

    # Health check first
    try:
        resp = client.get("/v1/healthz")
        resp.raise_for_status()
        print(f"Bot healthz: {resp.json()}")
    except Exception as exc:
        print(f"ERROR: bot not reachable at {args.bot_url}: {exc}", file=sys.stderr)
        sys.exit(1)

    pushed_categories, pushed_merchants, pushed_customers = set(), set(), set()
    output_lines = []
    failures = []

    for pair in pairs:
        test_id = pair["test_id"]
        merchant_path = expanded_dir / "merchants" / f"{pair['merchant_id']}.json"
        trigger_path = expanded_dir / "triggers" / f"{pair['trigger_id']}.json"

        if not merchant_path.exists() or not trigger_path.exists():
            failures.append((test_id, "missing merchant/trigger file in expanded dataset"))
            continue

        merchant_payload = load_json(merchant_path)
        trigger_payload = load_json(trigger_path)
        category_slug = merchant_payload["category_slug"]
        category_path = expanded_dir / "categories" / f"{category_slug}.json"

        try:
            if category_slug not in pushed_categories:
                push_context(client, "category", category_slug, load_json(category_path))
                pushed_categories.add(category_slug)

            if pair["merchant_id"] not in pushed_merchants:
                push_context(client, "merchant", pair["merchant_id"], merchant_payload)
                pushed_merchants.add(pair["merchant_id"])

            if pair.get("customer_id"):
                customer_path = expanded_dir / "customers" / f"{pair['customer_id']}.json"
                if customer_path.exists() and pair["customer_id"] not in pushed_customers:
                    push_context(client, "customer", pair["customer_id"], load_json(customer_path))
                    pushed_customers.add(pair["customer_id"])

            push_context(client, "trigger", pair["trigger_id"], trigger_payload)

            now_iso = safe_now_before_expiry(trigger_payload)
            resp = client.post("/v1/tick", json={"now": now_iso, "available_triggers": [pair["trigger_id"]]})
            resp.raise_for_status()
            actions = resp.json().get("actions", [])

            if not actions:
                failures.append((test_id, "bot returned no action for this trigger"))
                continue

            action = actions[0]
            output_lines.append({
                "test_id": test_id,
                "body": action["body"],
                "cta": action["cta"],
                "send_as": action["send_as"],
                "suppression_key": action["suppression_key"],
                "rationale": action["rationale"],
            })
            print(f"[{test_id}] OK — {action['body'][:70]}...")

        except Exception as exc:
            failures.append((test_id, str(exc)))
            print(f"[{test_id}] FAILED: {exc}", file=sys.stderr)

        time.sleep(0.05)  # gentle pacing, well under the judge's own rate cap

    out_path = Path(args.out)
    with out_path.open("w") as f:
        for line in output_lines:
            f.write(json.dumps(line, ensure_ascii=False) + "\n")

    print(f"\nWrote {len(output_lines)}/{len(pairs)} lines to {out_path}")
    if failures:
        print(f"\n{len(failures)} FAILURES:")
        for test_id, reason in failures:
            print(f"  {test_id}: {reason}")
        sys.exit(1 if len(output_lines) < len(pairs) else 0)


if __name__ == "__main__":
    main()
